name: fortran-src
version: '0.8.0'
synopsis: Parsers and analyses for Fortran standards 66, 77, 90, 95 and 2003 (partial).
description: >-
  Provides lexing, parsing, and basic analyses of Fortran code covering
  standards: FORTRAN 66, FORTRAN 77, Fortran 90, Fortran 95, Fortran 2003
  (partial) and some legacy extensions. Includes data flow and basic block
  analysis, a renamer, and type analysis. For example usage, see the
  @<https://hackage.haskell.org/package/camfort CamFort>@ project, which uses
  fortran-src as its front end.
tested-with: GHC >= 8.4
github: camfort/fortran-src
bug-reports: https://github.com/camfort/fortran-src/issues
author: [Mistral Contrastin, Matthew Danish, Dominic Orchard, Andrew Rice]
maintainer: [me@madgen.net, Ben Orchard]
category: Language
license: Apache-2.0
license-file: LICENSE

extra-source-files:
- README.md
- CHANGELOG.md
- test-data/**/*

# 2022-01-25: raehik: the essentials + handful of syntax (most in GHC2021)
default-extensions:
# essential
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- PolyKinds
- LambdaCase
# deriving-related
- DerivingStrategies
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift
# less essential but still gimmes
- BangPatterns
- TupleSections

dependencies:
- base >=4.6 && <5
- mtl >=2.2 && <3
- array >=0.5 && <0.6
- uniplate >=1.6 && <2
- GenericPretty >=1.2.2 && <2
- pretty >=1.1 && <2
- containers >=0.5 && <0.7
- text >=1.2 && <2
- bytestring >=0.10 && <0.12
- binary >=0.8.3.0 && <0.11
- filepath >=1.4 && <2
- directory >=1.2 && <2
- fgl >=5 && <6
- deepseq >=1.4 && <1.5
- filepath >=1.4 && <1.5
- temporary >=1.2 && <1.4
- either ^>=5.0.1.1

# --pedantic for building (not used for stack ghci)
ghc-options:
- -Wall
#- -Werror # appears bad to do in distribution, can be useful for development

library:
  source-dirs: src
  ghc-options: -fno-warn-tabs
  build-tools:
  - alex >=3.1
  - happy >=1.19

executables:
  fortran-src:
    source-dirs: app
    main: Main.hs
    ghc-options: -fno-warn-tabs
    dependencies:
    - fortran-src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover
    dependencies:
    - fortran-src
    - deepseq >=1.4 && <1.5
    - hspec >=2.2 && <3
    - QuickCheck >=2.10 && <2.15
