name: fortran-src
version: '0.5.0'
synopsis: Parsers and analyses for Fortran standards 66, 77, 90 and 95.
description: ! 'Provides lexing, parsing, and basic analyses of Fortran code covering
  standards: FORTRAN 66, FORTRAN 77, Fortran 90, and Fortran 95 and some legacy extensions.
  Includes data flow and basic block analysis, a renamer, and type analysis. For example
  usage, see the ''camfort'' project, which uses fortran-src as its front end.'
category: Language
author: Mistral Contrastin, Matthew Danish, Dominic Orchard, Andrew Rice
maintainer: me@madgen.net
license: Apache-2.0
github: camfort/fortran-src
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >=4.6 && <5
- mtl >=2.2 && <3
- array >=0.5 && <0.6
- uniplate >=1.6 && <2
- GenericPretty >=1.2.2 && <2
- pretty >=1.1 && <2
- containers >=0.5 && <0.7
- text >=1.2 && <2
- bytestring >=0.10 && <0.12
- binary >=0.8.3.0 && <0.11
- filepath >=1.4 && <2
- directory >=1.2 && <2
- fgl >=5 && <6
- deepseq >=1.4 && <1.5
- filepath >=1.4 && <1.5
- temporary >=1.2 && <1.4

# --pedantic for building (not used for stack ghci)
ghc-options:
- -Wall
#- -Werror # appears bad to do in distribution, can be useful for development

library:
  source-dirs: src
  ghc-options: -fno-warn-tabs
  build-tools:
  - alex >=3.1
  - happy >=1.19
  other-modules: []
  exposed-modules:
  - Language.Fortran.Analysis.SemanticTypes
  - Language.Fortran.Analysis
  - Language.Fortran.Analysis.Renaming
  - Language.Fortran.Analysis.ModGraph
  - Language.Fortran.Analysis.Types
  - Language.Fortran.Analysis.BBlocks
  - Language.Fortran.Analysis.DataFlow
  - Language.Fortran.AST
  - Language.Fortran.AST.AList
  - Language.Fortran.Version
  - Language.Fortran.LValue
  - Language.Fortran.Intrinsics
  - Language.Fortran.Lexer.FixedForm
  - Language.Fortran.Lexer.FreeForm
  - Language.Fortran.ParserMonad
  - Language.Fortran.Parser.Any
  - Language.Fortran.Parser.Fortran66
  - Language.Fortran.Parser.Fortran77
  - Language.Fortran.Parser.Fortran90
  - Language.Fortran.Parser.Fortran95
  - Language.Fortran.Parser.Fortran2003
  - Language.Fortran.Parser.Utils
  - Language.Fortran.PrettyPrint
  - Language.Fortran.Transformation.Disambiguation.Function
  - Language.Fortran.Transformation.Disambiguation.Intrinsic
  - Language.Fortran.Transformation.Grouping
  - Language.Fortran.Transformation.TransformMonad
  - Language.Fortran.Transformer
  - Language.Fortran.Util.Position
  - Language.Fortran.Util.FirstParameter
  - Language.Fortran.Util.SecondParameter
  - Language.Fortran.Util.ModFile
  - Language.Fortran.Util.Files
  - Language.Fortran.Rewriter
  - Language.Fortran.Rewriter.Internal

executables:
  fortran-src:
    main: src/Main.hs
    ghc-options: -fno-warn-tabs
    dependencies:
    - fortran-src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover
    dependencies:
    - fortran-src
    - deepseq >=1.4 && <1.5
    - hspec >=2.2 && <3

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
    - fortran-src
    - criterion >= 1.5 && <1.6
