name: CI

on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronized

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cache Stack downloaded packages
      uses: actions/cache@v2
      with:
        path: |
          $HOME/.stack
          .stack-work
        key: ${{ runner.os }}
    - name: install project dependencies
      run: stack --no-terminal test --only-dependencies
    - name: build and run tests
      run: stack --no-terminal haddock --test --no-haddock-deps
